repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.2
    hooks:
      - id: ruff # Linter
        args: ["--select", "I", "--fix"]  # Automatically fix issues where possible
      - id: ruff-format # Formatter

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Specify the version you want to use
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict

  # Docker file linter
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        name: Lint Dockerfiles
        files: Dockerfile
