version: "3.8"

services:
  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_KIND=redis
      - DATABASE_HOST=redis  
      - DATABASE_PORT=6379   
      - PYTHONHTTPSVERIFY=0
    depends_on:
      - redis         
    ports:
      - "8080:8080"

  redis:
    image: "redis:latest"  
    container_name: redis_cache
    ports:
      - "6379:6379"