- name: Configure Git
  hosts: localhost
  tasks:
    - name: Set Git username
      git_config:
        name: user.name
        value: "{{ git_user_name }}"
        scope: global

    - name: Set Git email
      git_config:
        name: user.email
        value: "{{ git_user_email }}"
        scope: global

