name: Build, Push Docker Image & Deploy Infrastructure with Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ACR_NAME: ${{ secrets.ACR_NAME }}
  IMAGE_NAME: 'embedding_service'
  IMAGE_TAG: 'latest'
  TF_WORKSPACE: 'infra'
  TF_VARS: '-var location=eucentral'  # Example of passing variables to Terraform

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry (ACR)
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/$IMAGE_NAME:$IMAGE_TAG .

    - name: Push Docker image to ACR
      run: |
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/$IMAGE_NAME:$IMAGE_TAG

  terraform-deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '~>1.9.8'  # Specify your desired Terraform version

    - name: Terraform Init
      run: |
        cd $TF_WORKSPACE
        terraform init

    - name: Terraform Plan
      run: |
        cd $TF_WORKSPACE
        terraform plan $TF_VARS

    - name: Terraform Apply
      run: |
        cd $TF_WORKSPACE
        terraform apply -auto-approve $TF_VARS
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
